#!/usr/local/bin/php
<?php


passthru('clear');


// retrieve information from composer.json
$projectInfo = json_decode(file_get_contents('composer.json'), true);
$masterVersion = $projectInfo['extra']['branch-alias']['dev-master'];
$nextMinor = explode('-', $masterVersion)[0];


// get information from repository
$currentBranch = shell_exec('git branch | grep "*"');
$currentRelease = floatval(substr($currentBranch, 2, strlen($currentBranch)));
$describe = shell_exec('git describe --tags');
$descriptions = explode('-', $describe);
$version = explode('.', $descriptions[0]);
$major = explode('.', $version[0])[0];
$minor = explode('.', $version[1])[0];
$patch = explode('.', $version[2])[0];
$patch++;


// if current is next major change major and minor
if ($nextMinor != $major.'.'.$minor) {
    $descriptions = explode('-', $nextMinor);
    $version = explode('.', $descriptions[0]);
    $major = explode('.', $version[0])[0];
    $minor = explode('.', $version[1])[0];
    $patch = 0;
}


// tag repository
ob_start();
$command = 'git tag ' . $major . '.' . $minor . '.' . $patch . ' 2>&1';
shell_exec($command);
$buffer = ob_get_contents();


// push tag
$alreadyCreatedTag = strpos($buffer, 'already') == 0 ? true : false;
if (!$alreadyCreatedTag) {
    passthru("git describe --tags");
    passthru("git push origin $major.$minor.$patch");
}


// log information
if ($alreadyCreatedTag) {
    echo "Already tagged with $major.$minor.$patch";
}
